name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  "Ubuntu":
    strategy:
      fail-fast: false
      matrix:
        version:
          - "16.04"
          - "18.04"
          - "20.04"
          - "22.04"
          - "24.04"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: docker build --tag build:ubuntu-${{ matrix.version }} --build-arg version=${{ matrix.version }} docker/ubuntu
        name: "docker build"
      - run: docker run --detach --interactive --name build --volume $PWD:/goestools build:ubuntu-${{ matrix.version }}
        name: "docker run"
      - run: docker exec -t build /run_cmake.sh
        name: "cmake"
      - run: docker exec -t build /run_compile.sh
        name: "make"
