name: Build docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: 'pip'
      - run: pip install -r docs/requirements.txt
      - run: make html
        working-directory: docs
