name: Documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  "Build":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: 'pip'
      - run: pip install -r docs/requirements.txt
      - run: make html
        working-directory: docs
      - uses: actions/upload-artifact@v2
        with:
          path: docs/_build/html

  "Deploy":
    needs: "Build"
    # if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/gh-pages
      # Remove all tracked files such that we're left with a snapshot of the artifact.
      - run: git ls-files -z | xargs -0 rm -f
      - uses: actions/download-artifact@v2
      - run: rsync -a artifact/ .
      - run: rm -rf artifact
      - run: git add -A
      - run: git commit -m "Snapshot refs/heads/master@$(git rev-parse --short refs/heads/master)"
      - run: git push origin gh-pages
